# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.url: 'https://api.lucien-brd.com'
    app.client.url: 'https://lucien-brd.com'
    app.assets.images.blogs: '%app.url%/assets/images/blogs/'
    app.assets.documents.blogs: '%app.url%/assets/documents/blogs/'
    app.assets.documents.cv: '%app.url%/assets/documents/cv/'
    app.assets.email: '%app.url%/assets/email/'
    app.assets.images.comments: '%app.url%/assets/images/comments/'
    app.assets.documents.download: '%app.url%/assets/documents/download/'
    app.assets.images.educations: '%app.url%/assets/images/educations/'
    app.assets.documents.politic: '%app.url%/assets/documents/politic/'
    app.assets.images.projects: '%app.url%/assets/images/projects/'
    app.assets.documents.projects: '%app.url%/assets/documents/projects/'
    app.assets.images.services: '%app.url%/assets/images/services/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
